### ISSUE TITLE
can you update to the latest pcre-16.dll version

### ISSUE THREAD

**Issue by loquat** [tannerhelland/PCRE2-VB6-DLL#2]
we can see the latest version is 10.37 now, i have tried to compile but failed.

**Comment by tannerhelland** [comment]
Hello @loquat .  I apologize that it's taken me a long time to respond to your comment.

There is a better version of this project here (maintained by the incomparable @jpbro from vbforums):

https://github.com/jpbro/VbPcre2/

Detailed instructions for compiling a copy of pcre-16 by yourself can also be found at that repository:

https://github.com/jpbro/VbPcre2/issues/24

I'm afraid I don't have a lot of time for VB6 development these days, but if you are unable to find what you need at the links above, please reply here and I will try to update this repository in the coming days/weeks.

**Comment by loquat** [comment]
Thank you Tannerhelland, i have compiled the latest version pcre2 10.37, by learning your compiling project.

**Comment by tannerhelland** [comment]
Great job, @loquat !  It's a big accomplishment for a VB6 developer to custom-build a project like PCRE2.  👍 

I will close this issue for now.  Good luck with your project.
